[bridge]
# [Required] TCP port number to listen for connections on.
tcp-port = 7000

# [Required] Serial port name. Example below is Unix name. Windows might look
# something such as "COM1"
serial-port = "/dev/ttys000"

# [Optional] If specified a connection from this IP address will
# pause communication with any other TCP connection (current or future).
priority-client = "192.168.1.111"

# [Optional] If priority client is being used then non-priority client 
# will receive PAUSE and RESUME commands whenever a priority client is connected.
control-command-format = "~~%s\r"
